Lab2
hxnchar/laba2web pull request #3
Opened 2021-12-31 12:58 UTC by hxnchar

2021-12-31 15:06 UTC, nosovk commented on .eslintrc.json
> +  "env": {
еще должен быть блок plugins с сонаром

2021-12-31 15:07 UTC, nosovk commented on .prettierignore
> +package-lock.json
этот файл можно удалить т.к. мы для всего можем использовать набор паттернов из gitignore

2021-12-31 15:09 UTC, nosovk commented on api/sendMail.js
> +    try {
у нас сразу несколько подобных конструкций try catch - возможно можно объединить их в одну?

2021-12-31 15:21 UTC, nosovk commented on src/Form.jsx
> +      setResultText('Error');
если произошла ошибка не должны ли мы убрать спиннер загрузки? Или оставим его навечно чтобы человек не мог повторить запрос?

2021-12-31 15:21 UTC, nosovk commented on src/Form.jsx
> +    <form onSubmit={e => onSubmit(e)}>
можно указать просто `onSubmit={onSubmit}`

2021-12-31 15:23 UTC, nosovk commented
<img width="786" alt="image" src="https://user-images.githubusercontent.com/1398808/147830333-e77f474d-9dc8-496a-9cf3-4cf46c2eb876.png">

2021-12-31 15:25 UTC, nosovk commented
https://jsonapi.org/format/#errors
по поводу success: true и т.п. - есть спецификация как делать, лучше как в ней делать т.к. там более общие подходы к которым трудно подобрать исключение

2022-01-06 11:33 UTC, DanielJorn requested changes

2022-01-06 11:33 UTC, DanielJorn commented on api/sendMail.js
> +    port: 587,
port to env

2022-01-06 11:33 UTC, DanielJorn commented on api/sendMail.js
> +  }
этот блок if можно сильно упростить (удалить)

2022-01-06 11:33 UTC, DanielJorn commented on api/sendMail.js
> +    throw new Error();
Передавать сообщение об ошибке

2022-01-06 11:33 UTC, DanielJorn commented on package.json
> +    "prettier": "^2.5.1",
prettier dev dependency

2022-01-06 11:33 UTC, DanielJorn commented on src/App.css
> +  background-color: #282c34;
CSS VARS ?>?>??>?>?>>??>?>

2022-01-06 14:49 UTC, Ekedani commented on src/App.css
> +  color: white;
Kill me

2022-01-06 14:50 UTC, hxnchar commented on src/App.css
> +  color: white;
😭

2022-01-06 14:56 UTC, Ekedani commented
![image](https://user-images.githubusercontent.com/71406730/148402229-120d14fd-eda4-4ef3-918d-1d037bb03a47.png)
You should use this

2022-01-08 14:49 UTC, nosovk commented on api/sendMail.js
> +    throw new Error(error?.message ?? 'Send Error');
CustomError(500, error?.message ?? 'Send Error');
так не понятно какой код будет

2022-01-08 14:49 UTC, nosovk commented on package.json
> +    "format:check": "prettier --check . --ignore-path .gitignore --ignore-path .prettierignore",
--ignore-path может же gitignore принимать и тогда prettierignore можно удалить

2022-01-08 14:50 UTC, nosovk commented on src/App.css
> +  color: white;
ага, css vars :)

2022-01-08 14:51 UTC, nosovk commented on src/Form.jsx
> +      setDisableButton(false);
setCountSpinners(n => n - 1);
      setDisableButton(false);

веротяно можно вынести в finally или аналог?

2022-01-10 18:54 UTC, nosovk commented on src/App.css
> +  color: white;
а чего этот решили оставит @hxnchar?

2022-01-10 18:54 UTC, nosovk commented on src/App.css
> +  color: white;
а чего этот решили оставит @hxnchar?

2022-01-10 18:55 UTC, nosovk commented
поправить последний коммент и merge

2022-01-10 22:33 UTC, hxnchar commented
> поправить последний коммент и merge

Я пофиксил, но outdated не появилось почему-то

2022-01-10 22:33 UTC, merged